version: '3.8'
services:
  bot:
    build: .
    container_name: fitness-bot
    volumes:
      - ./db:/app/db  # Persist SQLite DB
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./webadmin/frontend
    container_name: fitness-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build:
      context: ./webadmin/backend
    container_name: fitness-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
